### ISSUE TITLE
card-mod styling not working

### ISSUE THREAD

**Issue by mateuszdrab** [htmltiger/numberbox-card#26]
Hi

I'm trying to use the card-mod to add some margin on the left of the unit with no success.

I'm using examples provided but none of them take effect on the card.

I posted a request here as well: https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744/2413?u=mateuszdrab

Can you help?

I believe it's something to do with the shadow roots that I just can't work around.

Thanks

**Comment by htmltiger** [comment]
Its on the first page, last screenshot

  - entity: input_number.my_slider
    type: 'custom:numberbox-card'
    icon_plus: 'mdi:chevron-up'
    icon_minus: 'mdi:chevron-down'
    style: |
      .cur-num{font-size:25px !important}
      .cur-unit{color:orange; font-size:100% !important; opacity:1 !important}
      .grid-left{color:red}
      .grid-right{color:blue}

**Comment by mateuszdrab** [comment]
Thanks for replying.

Unfortunately, I tried it all out. It just won't work.

![image](https://user-images.githubusercontent.com/26556541/144716280-8cb16a7d-0e31-4290-92e8-4f5cef955df2.png)

**Comment by htmltiger** [comment]
Try this one 
copy everything
```
type: entities
title: Example
show_header_toggle: false
entities:
  - entity: input_number.bedtime_delay
    type: 'custom:numberbox-card'
    icon_plus: 'mdi:chevron-up'
    icon_minus: 'mdi:chevron-down'
    style: |
      .cur-num{font-size:25px !important}
      .cur-unit{color:orange; font-size:100% !important; opacity:1 !important}
      .grid-left{color:red}
      .grid-right{color:blue}
```

**Comment by mateuszdrab** [comment]
That does work. Hmm, so it needs to be in the entities card?
I understand I can address multiple numberbox cards by defining style for the entities card as well, right?

**Comment by htmltiger** [comment]
I have tried this and it works with entity
```
type: custom:numberbox-card
entity: number.bedtime_delay
card_mod:
      style: |
        ha-card .cur-num {
          color: green;
        }
```

**Comment by mateuszdrab** [comment]
Yeah that works on a new card, but it doesn't seem to work inside my vertical-stack card. It only works when there's entities inside the vertical-stack and then the numberbox-card inside it. Either way - don't mind if being inside the entities card. It gets an extra margin, but it's fine as well, looks neater actually. 
I'm going to have a look at the styling someone posted on https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744/2413?u=mateuszdrab as it has some more examples.

**Comment by ildar170975** [comment]
> I have tried this and it works with entity

If it is supposed to be a separate card - this styling does not work on my setup((((.
Moreover - the whole card is not displayed if I add `card_mod` section, it is displayed only in the Editor (and the style MAY BE applied then but MAY NOT).

-------------------------------

Surely there is a problem here.

If this card is supposed to be used inside Entities card - styling works OK, here my examples: https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744/2416?u=ildar_gabdullin
And the 'ha-card' keyword is not supposed to be used here, use `:host` or DOM navigation.

But if this card is used as a separate card (not inside the Entities card) - card_mod DOES NOT work.
See the example:
```
type: custom:numberbox-card
entity: input_number.test_number
name: XXXXXXXXXXXX
card_mod:
  style: |
    ha-card {
      --paper-item-icon-color: green;
    }
```
![image](https://user-images.githubusercontent.com/71872483/144774370-642969b6-61a8-4ae1-8648-3c223e606447.png)

I only can style this card by using `mod-card` - this is needed if you decide to create a `decluttering-card` based on this `numberbox-card`.
Then these styles work:
```
    type: custom:mod-card
    card:
      type: custom:numberbox-card
      entity: ....
    card_mod:
      style:
        numberbox-card$: |
          .grid-content.grid-left {
            ...
          }
          ha-card.noborder {
            --paper-item-icon-color: red;
          }
```
But - since the `numberbox-card` already has the `ha-card` element, there are errors in Code Inspector (kind of "You cannot use mod-card with cards which already have ha-card").

My proposals:
- either remove `ha-card` element since it does not work with card-mod;
- or - much better!!!! - fix using `ha-card` element for card-mod styling.

Look at the `custom:bar-card` - it has `ha-card` element and may be styled as a card inside Entities card and as a separate card as well.

**Comment by mateuszdrab** [comment]
That explains a lot. I used the mod-card with another custom element which didn't implement ha-card however considering this one had ha-card. I expected it to work.  Hopefully it can be easily fixed.
